### ISSUE TITLE
Artemis plugin no longer works

### ISSUE THREAD

**Issue by fedorov** [SlicerHeart/SlicerHeart#14]
Report from Alan Priester below:

I have been receiving complaints from TCIA users that the ultrasound images from the Prostate-MRI-US-Biopsy dataset no longer load properly into 3D Slicer. I downloaded the most recent stable release (4.11.2021.0226) and confirmed that ultrasound data no longer loads correctly, with or without the "SlicerHeart" and "Quantitative Reporting" extensions. The following warning is displayed during attempts to load ultrasound image data:

"115: US [633] [Image sequence]: Image spacing may need to be calibrated for accurate size measurements."

The following screen capture shows the (erroneous) result:

![image](https://user-images.githubusercontent.com/313942/113922755-af3fc980-97b5-11eb-8cf8-3d07739991c3.png)

It would seem that a Slicer release between June 2020 and February 2021 compromised this functionality--can you please investigate and advise?

**Comment by lassoan** [comment]
Maybe the confidence value of the Artemis reader needs to be set to a higher value. Can you send a download link to a sample data set?

**Comment by fedorov** [comment]
I can't make time to investigate right now, but wanted to add an issue to make sure it is not lost right away as I received the email from the user. I haven't looked into it yet.

**Comment by lassoan** [comment]
I can look into it if you can share a sample data set.

**Comment by fedorov** [comment]
@lassoan I submitted a PR. The dataset is here: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=68550661.
