### ISSUE TITLE
”https://github.com/GEUltrasound/GE_CVUS_Loader/releases/“ is unavailable?

### ISSUE THREAD

**Issue by Huaweidev** [SlicerHeart/SlicerHeart#17]
”https://github.com/GEUltrasound/GE_CVUS_Loader/releases/“ is unavailable? How to download the GE_CVUS_Loader?

**Comment by lassoan** [comment]
You need to register to GE's developer program. See details in the README.MD file.

**Comment by Huaweidev** [comment]
> You need to register to GE's developer program. See details in the README.MD file.
I found the `https://github.com/GEUltrasound` and `This organization has no public repositories.` after registered just now.
But there is no necessary star symbol beside the `GitHub Username (Please provide your public GitHub username if you are interested in accessing our AppAPI repository that will enable you to build ultrasound apps that can run directly on-device, as well as real-time network streaming of 2D/3D ultrasound data.)`, I don't know how to update my github username to `GE Ultrasound`.

**Comment by lassoan** [comment]
You need to wait until they add you to the organization. Allow at least a few days for them to do this.

**Comment by Huaweidev** [comment]
Everybody don't forget to add GitHub username to this text box, even though there is no mandatory star symbol besides it, like the picture below.


![06-06_22-48](https://user-images.githubusercontent.com/10258421/120929121-64412480-c71a-11eb-9ba4-d4c7aff63b3f.png)
