### ISSUE TITLE
anybody who shares the process of building SlicerHeart from source?

### ISSUE THREAD

**Issue by whucsu** [SlicerHeart/SlicerHeart#20]
anybody who shares the process of building SlicerHeart from source?
thanks

**Comment by lassoan** [comment]
SlicerHeart extension can be built as all other Slicer extensions. If the [instructions in Slicer documentation](https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#build-an-extension) are not clear then please post on the [Slicer forum](https://discourse.slicer.org).
