### ISSUE TITLE
Type inconsistency in an if block at DicomUltrasoundPlugin.py

### ISSUE THREAD

**Issue by vc-k** [SlicerHeart/SlicerHeart#9]
Hi,

I've found a bug that causes loading a Philips affinity 3d ultrasound file without considering voxel spacing data.

The fix is quite easy. In the if block below there is a comparison between `data_element.value.rstrip()` and `privateCreator` values but `data_element.value` is a bytes object and `privateCreator` is a string.

My fix:
I've fixed the if block by encoding `privateCreator` value. `privateCreator.encode()`

Regards.

```python
def findPrivateTag(ds, group, element, privateCreator):
  """Helper function to get private tag from private creator name"""
  for tag, data_element in ds.items():
    if (tag.group == group) and (tag.element < 0x0100) and (data_element.value.rstrip() == privateCreator):
      return dicom.tag.Tag(group, (tag.element << 8) + element)
  return None
```

**Comment by lassoan** [comment]
Thank you! Is this fix for Slicer-4.10 (Python2) or Slicer-4.11 (Python3)?

Can you share a small sample data set that I can test on? 

@fedorov can you have a look at this, too?

**Comment by vc-k** [comment]
Hi @lassoan ,

I was working with Slicer-4.11 when i had this issue. I grabbed the image from [here.](https://discourse.slicer.org/t/problem-importing-a-volumen-with-a-phillips-affinity-50/5065)

I've checked this for Slicer-4.10 but i got a different error below. I might have installed it incorrectly or need to install `pydicom` package for Python2 maybe even Python2.

I don't have time to chase it today but if same thing occurs in Slicer-4.10 i think it will solve the issue for both versions.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/gregor/AppData/Roaming/NA-MIC/Extensions-28257/SlicerHeart/lib/Slicer-4.10/qt-scripted-modules/DicomUltrasoundPlugin.py", line 6, in <module>
    import pydicom as dicom
ImportError: No module named pydicom
```

**Comment by lassoan** [comment]
`pydicom` package was called just `dicom` earlier. A try/except block would need to be added to support both `dicom` and `pydicom` names.

**Comment by fedorov** [comment]
I agree with @lassoan - would be best if you could share a sample dataset to test, since this code is indeed working for other datasets. At lest perhaps you could do [`dcmdump`](https://support.dcmtk.org/docs/dcmdump.html) for the file where you experience this issue, and share the private creator field? Is it that your dataset private creator has some non-ASCII characters?

**Comment by lassoan** [comment]
I've fixed this by adding:

      if type(data_element.value) == bytes:
        data_element_value = data_element_value.decode()

This makes the function work with both `bytes` and `string` type data_element.value.
